// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gflgbxalujnmfsdvwiqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmbGdieGFsdWpubWZzZHZ3aXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDk4ODIsImV4cCI6MjA2NDcyNTg4Mn0.UJLU494r6TNmwIwlK1hXvcHmFr7xUergyO6LDuS0z3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);